// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5zgGwD-W6KQp6FkqNsUNXr4hvq6E8GvI',
    appId: '1:408144020751:web:8159d44549d6fd335f2a7a',
    messagingSenderId: '408144020751',
    projectId: 'quick-form-4fdd6',
    authDomain: 'quick-form-4fdd6.firebaseapp.com',
    storageBucket: 'quick-form-4fdd6.firebasestorage.app',
    measurementId: 'G-ZCHZE5QBWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBENqvDPw4IiEPFAyzUU3PkBFPNkoJvKe0',
    appId: '1:408144020751:android:e210b48498fecdf35f2a7a',
    messagingSenderId: '408144020751',
    projectId: 'quick-form-4fdd6',
    storageBucket: 'quick-form-4fdd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8OAt6zkL4A6PhZj1haj0v5C9T9tPPomE',
    appId: '1:408144020751:ios:3b267a8f982287c25f2a7a',
    messagingSenderId: '408144020751',
    projectId: 'quick-form-4fdd6',
    storageBucket: 'quick-form-4fdd6.firebasestorage.app',
    iosBundleId: 'com.example.quickform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8OAt6zkL4A6PhZj1haj0v5C9T9tPPomE',
    appId: '1:408144020751:ios:3b267a8f982287c25f2a7a',
    messagingSenderId: '408144020751',
    projectId: 'quick-form-4fdd6',
    storageBucket: 'quick-form-4fdd6.firebasestorage.app',
    iosBundleId: 'com.example.quickform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5zgGwD-W6KQp6FkqNsUNXr4hvq6E8GvI',
    appId: '1:408144020751:web:7beaab7d3504ebd15f2a7a',
    messagingSenderId: '408144020751',
    projectId: 'quick-form-4fdd6',
    authDomain: 'quick-form-4fdd6.firebaseapp.com',
    storageBucket: 'quick-form-4fdd6.firebasestorage.app',
    measurementId: 'G-7S7N6RVXLB',
  );
}
