// import 'package:device_preview/device_preview.dart';
// import 'package:flutter/material.dart';
// import 'package:provider/provider.dart';
// import 'package:firebase_core/firebase_core.dart';
//
// import 'Admin/Homepage.dart';
// import 'Admin/createformpage.dart';
// import 'Admin/form_provider.dart';
// import 'Admin/profile_page.dart';
// import 'Admin/user_provider.dart';
// import 'firebase_options.dart'; // generated by flutterfire CLI
//
// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//
//   // Initialize Firebase
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//
//   runApp(
//     MultiProvider(
//       providers: [
//         ChangeNotifierProvider(create: (_) => FormsProvider()),
//         ChangeNotifierProvider(create: (_) => UserProvider()),
//       ],
//       child: DevicePreview(
//         enabled: true, // Disable in production
//         builder: (context) => const MyApp(),
//       ),
//     ),
//   );
// }
//
// class MyApp extends StatelessWidget {
//   const MyApp({super.key});
//
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       locale: DevicePreview.locale(context),
//       builder: DevicePreview.appBuilder,
//       title: 'Quick Form',
//       theme: ThemeData(primarySwatch: Colors.lightBlue),
//       initialRoute: '/',
//       routes: {
//         '/': (context) => const HomePage(),
//         '/create': (context) => const CreateFormPage(),
//         '/profile': (context) => const ProfilePage(),
//       },
//     );
//   }
// }


import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:quickform/firebase_options.dart';

import 'Profile/Roles_Screen.dart';

void main()async{
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: RolesScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}
